// packages/react/src/Fill/SiThumbDownAlt2.js
import * as React from "react";
import { forwardRef, memo } from "react";
import { useId } from "react";
const SvgSiThumbDownAlt2 = ({ title, titleId, ...props }, ref) => {
  const generatedId = useId();
  const validTitleId = titleId || generatedId;
  const isTitlePresent = !!title;
  return (
    <svg
      width="1em"
      height="1em"
      fill="none"
      viewBox="0 0 24 24"
      aria-hidden={!isTitlePresent}
      aria-labelledby={titleId}
      ref={ref}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fill="currentColor"
        d="M13.501 14.203a1 1 0 0 1 1-1h5.833a.6.6 0 0 0 .288-.071.7.7 0 0 0 .238-.21.78.78 0 0 0 .107-.664L18.66 4.502a.73.73 0 0 0-.25-.37.64.64 0 0 0-.284-.124l-.1-.008H8v7.265l3.945 4.896c.144.178.222.4.222.628v3.153c.36-.124.652-.32.866-.594.254-.326.468-.848.468-1.698zm2 3.447c0 1.196-.308 2.18-.89 2.927s-1.37 1.17-2.171 1.37l-.006.002a1.82 1.82 0 0 1-1.582-.363 1.86 1.86 0 0 1-.685-1.452V17.14l-2.428-3.013A1.8 1.8 0 0 1 6.2 15H2.8A1.8 1.8 0 0 1 1 13.2V2.8A1.8 1.8 0 0 1 2.8 1h3.4c.706 0 1.316.408 1.61 1h10.215c.579 0 1.14.192 1.598.542s.79.839.954 1.39l2.308 7.756a2.78 2.78 0 0 1-.397 2.396 2.7 2.7 0 0 1-.94.82 2.6 2.6 0 0 1-1.055.294l-.158.005h-4.834z"
      />
    </svg>
  );
};
SvgSiThumbDownAlt2.displayName = "SvgSiThumbDownAlt2";
const ForwardRef = forwardRef(SvgSiThumbDownAlt2);
const Memo = memo(ForwardRef);
export default Memo;

// packages/svelte/src/Fill/SiThumbDownAlt2.svelte
<script>
  const inner = "<path fill=\"currentColor\" d=\"M13.501 14.203a1 1 0 0 1 1-1h5.833a.6.6 0 0 0 .288-.071.7.7 0 0 0 .238-.21.782.782 0 0 0 .107-.664L18.66 4.502a.73.73 0 0 0-.25-.37.64.64 0 0 0-.284-.124l-.1-.008H8v7.265l3.945 4.896c.144.178.222.4.222.628v3.153c.36-.124.652-.32.866-.594.254-.326.468-.848.468-1.698zm2 3.447c0 1.196-.308 2.18-.89 2.927s-1.37 1.17-2.171 1.37l-.006.002a1.82 1.82 0 0 1-1.582-.363 1.86 1.86 0 0 1-.685-1.452V17.14l-2.428-3.013A1.8 1.8 0 0 1 6.2 15H2.8A1.8 1.8 0 0 1 1 13.2V2.8A1.8 1.8 0 0 1 2.8 1h3.4c.706 0 1.316.408 1.61 1h10.215c.579 0 1.14.192 1.598.542s.79.839.954 1.39l2.308 7.756a2.78 2.78 0 0 1-.397 2.396 2.7 2.7 0 0 1-.94.82 2.6 2.6 0 0 1-1.055.294l-.158.005h-4.834z\"/>";
  let { title, ...rest } = $props();
</script>

<svg
  xmlns="http://www.w3.org/2000/svg"
  width="1em"
  height="1em"
  fill="none"
  viewBox="0 0 24 24"
  aria-hidden={title ? undefined : 'true'}
  {...rest}
>
  {#if title}<title>{title}</title>{/if}
  {@html inner}
</svg>
