// packages/svelte/src/Fill/SiAiChecklist.svelte
<script>
  const inner = "<path fill=\"currentColor\" d=\"M22 18a1 1 0 1 1 0 2H12a1 1 0 0 1 0-2zm0-7a1 1 0 1 1 0 2H12a1 1 0 0 1 0-2zM7.293 2.293a1 1 0 1 1 1.414 1.414l-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 1 1 1.414-1.414L4 5.586zM22 4a1 1 0 1 1 0 2H12a1 1 0 0 1 0-2zM4.104 16.507c.288-.843 1.504-.844 1.792 0l.025.087.297 1.188 1.188.297c.959.24.96 1.603 0 1.843l-1.188.296-.297 1.188c-.24.959-1.602.959-1.842 0l-.297-1.188-1.188-.296c-.96-.24-.96-1.603 0-1.843l1.187-.297.298-1.188zM5 18.797a1 1 0 0 1-.205.203 1 1 0 0 1 .205.202A1 1 0 0 1 5.204 19 1 1 0 0 1 5 18.797m-.896-9.29c.298-.871 1.585-.842 1.817.087l.297 1.188 1.188.297c.96.24.96 1.603 0 1.842l-1.188.297-.297 1.188c-.24.96-1.602.96-1.842 0l-.297-1.188-1.188-.296c-.96-.24-.96-1.603 0-1.843l1.188-.297.297-1.188zM5 11.797a1 1 0 0 1-.204.203 1 1 0 0 1 .204.203A1 1 0 0 1 5.203 12 1 1 0 0 1 5 11.797\"/>";
  let { title, ...rest } = $props();
</script>

<svg
  xmlns="http://www.w3.org/2000/svg"
  width="1em"
  height="1em"
  fill="none"
  viewBox="0 0 24 24"
  aria-hidden={title ? undefined : 'true'}
  {...rest}
>
  {#if title}<title>{title}</title>{/if}
  {@html inner}
</svg>

// packages/react/src/Fill/SiAiChecklist.js
import * as React from "react";
import { forwardRef, memo } from "react";
import { useId } from "react";
const SvgSiAiChecklist = ({ title, titleId, ...props }, ref) => {
  const generatedId = useId();
  const validTitleId = titleId || generatedId;
  const isTitlePresent = !!title;
  return (
    <svg
      width="1em"
      height="1em"
      fill="none"
      viewBox="0 0 24 24"
      aria-hidden={!isTitlePresent}
      aria-labelledby={titleId}
      ref={ref}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fill="currentColor"
        d="M22 18a1 1 0 1 1 0 2H12a1 1 0 0 1 0-2zm0-7a1 1 0 1 1 0 2H12a1 1 0 0 1 0-2zM7.293 2.293a1 1 0 1 1 1.414 1.414l-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 1 1 1.414-1.414L4 5.586zM22 4a1 1 0 1 1 0 2H12a1 1 0 0 1 0-2zM4.104 16.507c.288-.843 1.504-.844 1.792 0l.025.087.297 1.188 1.188.297c.959.24.96 1.603 0 1.843l-1.188.296-.297 1.188c-.24.959-1.602.959-1.842 0l-.297-1.188-1.188-.296c-.96-.24-.96-1.603 0-1.843l1.187-.297.298-1.188zM5 18.797a1 1 0 0 1-.205.203 1 1 0 0 1 .205.202A1 1 0 0 1 5.204 19 1 1 0 0 1 5 18.797m-.896-9.29c.298-.871 1.585-.842 1.817.087l.297 1.188 1.188.297c.96.24.96 1.603 0 1.842l-1.188.297-.297 1.188c-.24.96-1.602.96-1.842 0l-.297-1.188-1.188-.296c-.96-.24-.96-1.603 0-1.843l1.188-.297.297-1.188zM5 11.797a1 1 0 0 1-.204.203 1 1 0 0 1 .204.203A1 1 0 0 1 5.203 12 1 1 0 0 1 5 11.797"
      />
    </svg>
  );
};
SvgSiAiChecklist.displayName = "SvgSiAiChecklist";
const ForwardRef = forwardRef(SvgSiAiChecklist);
const Memo = memo(ForwardRef);
export default Memo;
