// packages/svelte/src/Fill/SiFlowBranch.svelte
<script>
  const inner = "<path fill=\"currentColor\" d=\"M8 20a1 1 0 1 0-2 0 1 1 0 0 0 2 0M8 4a1 1 0 1 0-2 0 1 1 0 0 0 2 0m10 0a1 1 0 1 0-2 0 1 1 0 0 0 2 0m2 0a3 3 0 0 1-2 2.825v2.33c0 2.19-1.705 4.076-3.91 4.076H9.91c-.996 0-1.91.883-1.91 2.077v1.866A2.998 2.998 0 0 1 7 23a3 3 0 0 1-1-5.826V6.825A2.998 2.998 0 0 1 7 1a2.998 2.998 0 0 1 1 5.825v4.925c.56-.33 1.21-.52 1.91-.52h4.18c.996 0 1.91-.882 1.91-2.076V6.825A2.998 2.998 0 0 1 17 1a3 3 0 0 1 3 3\"/>";
  let { title, ...rest } = $props();
</script>

<svg
  xmlns="http://www.w3.org/2000/svg"
  width="1em"
  height="1em"
  fill="none"
  viewBox="0 0 24 24"
  aria-hidden={title ? undefined : 'true'}
  {...rest}
>
  {#if title}<title>{title}</title>{/if}
  {@html inner}
</svg>

// packages/react/src/Fill/SiFlowBranch.js
import * as React from "react";
import { forwardRef, memo } from "react";
import { useId } from "react";
const SvgSiFlowBranch = ({ title, titleId, ...props }, ref) => {
  const generatedId = useId();
  const validTitleId = titleId || generatedId;
  const isTitlePresent = !!title;
  return (
    <svg
      width="1em"
      height="1em"
      fill="none"
      viewBox="0 0 24 24"
      aria-hidden={!isTitlePresent}
      aria-labelledby={titleId}
      ref={ref}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fill="currentColor"
        d="M8 20a1 1 0 1 0-2 0 1 1 0 0 0 2 0M8 4a1 1 0 1 0-2 0 1 1 0 0 0 2 0m10 0a1 1 0 1 0-2 0 1 1 0 0 0 2 0m2 0a3 3 0 0 1-2 2.825v2.33c0 2.19-1.705 4.076-3.91 4.076H9.91c-.996 0-1.91.883-1.91 2.077v1.866A2.998 2.998 0 0 1 7 23a3 3 0 0 1-1-5.826V6.825A2.998 2.998 0 0 1 7 1a2.998 2.998 0 0 1 1 5.825v4.925c.56-.33 1.21-.52 1.91-.52h4.18c.996 0 1.91-.882 1.91-2.076V6.825A2.998 2.998 0 0 1 17 1a3 3 0 0 1 3 3"
      />
    </svg>
  );
};
SvgSiFlowBranch.displayName = "SvgSiFlowBranch";
const ForwardRef = forwardRef(SvgSiFlowBranch);
const Memo = memo(ForwardRef);
export default Memo;
