// packages/svelte/src/Fill/SiMonitorStop.svelte
<script>
  const inner = "<path fill=\"currentColor\" d=\"M15 19a1 1 0 1 1 0 2H9a1 1 0 1 1 0-2zM13.5 9v3h-3V9z\"/><path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M19.775 3.005A3.4 3.4 0 0 1 23 6.4v8.2a3.4 3.4 0 0 1-3.4 3.4H4.4A3.4 3.4 0 0 1 1 14.6V6.4A3.4 3.4 0 0 1 4.4 3h15.2zM10.3 7a1.8 1.8 0 0 0-1.8 1.8v3.4a1.8 1.8 0 0 0 1.8 1.8h3.4a1.8 1.8 0 0 0 1.8-1.8V8.8A1.8 1.8 0 0 0 13.7 7z\" clip-rule=\"evenodd\"/>";
  let { title, ...rest } = $props();
</script>

<svg
  xmlns="http://www.w3.org/2000/svg"
  width="1em"
  height="1em"
  fill="none"
  viewBox="0 0 24 24"
  aria-hidden={title ? undefined : 'true'}
  {...rest}
>
  {#if title}<title>{title}</title>{/if}
  {@html inner}
</svg>

// packages/react/src/Fill/SiMonitorStop.js
import * as React from "react";
import { forwardRef, memo } from "react";
import { useId } from "react";
const SvgSiMonitorStop = ({ title, titleId, ...props }, ref) => {
  const generatedId = useId();
  const validTitleId = titleId || generatedId;
  const isTitlePresent = !!title;
  return (
    <svg
      width="1em"
      height="1em"
      fill="none"
      viewBox="0 0 24 24"
      aria-hidden={!isTitlePresent}
      aria-labelledby={titleId}
      ref={ref}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fill="currentColor"
        d="M15 19a1 1 0 1 1 0 2H9a1 1 0 1 1 0-2zM13.5 9v3h-3V9z"
      />
      <path
        fill="currentColor"
        fillRule="evenodd"
        d="M19.775 3.005A3.4 3.4 0 0 1 23 6.4v8.2a3.4 3.4 0 0 1-3.4 3.4H4.4A3.4 3.4 0 0 1 1 14.6V6.4A3.4 3.4 0 0 1 4.4 3h15.2zM10.3 7a1.8 1.8 0 0 0-1.8 1.8v3.4a1.8 1.8 0 0 0 1.8 1.8h3.4a1.8 1.8 0 0 0 1.8-1.8V8.8A1.8 1.8 0 0 0 13.7 7z"
        clipRule="evenodd"
      />
    </svg>
  );
};
SvgSiMonitorStop.displayName = "SvgSiMonitorStop";
const ForwardRef = forwardRef(SvgSiMonitorStop);
const Memo = memo(ForwardRef);
export default Memo;
