// packages/svelte/src/Fill/SiPinAlt1.svelte
<script>
  const inner = "<path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M6.368 3.36a7.904 7.904 0 0 1 11.24-.027h.002l.015.015.001.002.01.01c3.142 3.16 3.15 8.226.038 11.355l-4.963 4.99a1 1 0 0 1-1.418 0l-4.962-4.99c-3.108-3.125-3.108-8.192 0-11.317zM12 5.5a3 3 0 1 0 0 6 3 3 0 0 0 0-6\" clip-rule=\"evenodd\"/><path fill=\"currentColor\" d=\"M16.47 16.812a1 1 0 0 1 1.16-.81c1.414.251 2.653.604 3.565 1.054.455.224.878.496 1.2.832.327.34.605.807.605 1.384 0 .907-.66 1.527-1.244 1.903-.628.405-1.47.732-2.422.991-1.918.523-4.51.834-7.334.834s-5.416-.311-7.334-.834c-.952-.26-1.794-.586-2.422-.991C1.661 20.799 1 20.179 1 19.272c0-.577.278-1.044.604-1.384.323-.336.746-.608 1.2-.832.913-.45 2.152-.803 3.566-1.054a1 1 0 0 1 .35 1.969c-1.322.235-2.356.546-3.032.879-.337.166-.538.314-.64.42.047.05.13.128.28.224.384.248 1.007.508 1.864.742C6.894 20.7 9.302 21 12 21c2.699 0 5.106-.3 6.808-.764.857-.234 1.48-.494 1.864-.742.15-.096.232-.174.28-.224-.104-.106-.303-.254-.64-.42-.676-.333-1.71-.644-3.033-.88a1 1 0 0 1-.81-1.158\"/>";
  let { title, ...rest } = $props();
</script>

<svg
  xmlns="http://www.w3.org/2000/svg"
  width="1em"
  height="1em"
  fill="none"
  viewBox="0 0 24 24"
  aria-hidden={title ? undefined : 'true'}
  {...rest}
>
  {#if title}<title>{title}</title>{/if}
  {@html inner}
</svg>

// packages/react/src/Fill/SiPinAlt1.js
import * as React from "react";
import { forwardRef, memo } from "react";
import { useId } from "react";
const SvgSiPinAlt1 = ({ title, titleId, ...props }, ref) => {
  const generatedId = useId();
  const validTitleId = titleId || generatedId;
  const isTitlePresent = !!title;
  return (
    <svg
      width="1em"
      height="1em"
      fill="none"
      viewBox="0 0 24 24"
      aria-hidden={!isTitlePresent}
      aria-labelledby={titleId}
      ref={ref}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fill="currentColor"
        fillRule="evenodd"
        d="M6.368 3.36a7.904 7.904 0 0 1 11.24-.027h.002l.015.015.001.002.01.01c3.142 3.16 3.15 8.226.038 11.355l-4.963 4.99a1 1 0 0 1-1.418 0l-4.962-4.99c-3.108-3.125-3.108-8.192 0-11.317zM12 5.5a3 3 0 1 0 0 6 3 3 0 0 0 0-6"
        clipRule="evenodd"
      />
      <path
        fill="currentColor"
        d="M16.47 16.812a1 1 0 0 1 1.16-.81c1.414.251 2.653.604 3.565 1.054.455.224.878.496 1.2.832.327.34.605.807.605 1.384 0 .907-.66 1.527-1.244 1.903-.628.405-1.47.732-2.422.991-1.918.523-4.51.834-7.334.834s-5.416-.311-7.334-.834c-.952-.26-1.794-.586-2.422-.991C1.661 20.799 1 20.179 1 19.272c0-.577.278-1.044.604-1.384.323-.336.746-.608 1.2-.832.913-.45 2.152-.803 3.566-1.054a1 1 0 0 1 .35 1.969c-1.322.235-2.356.546-3.032.879-.337.166-.538.314-.64.42.047.05.13.128.28.224.384.248 1.007.508 1.864.742C6.894 20.7 9.302 21 12 21c2.699 0 5.106-.3 6.808-.764.857-.234 1.48-.494 1.864-.742.15-.096.232-.174.28-.224-.104-.106-.303-.254-.64-.42-.676-.333-1.71-.644-3.033-.88a1 1 0 0 1-.81-1.158"
      />
    </svg>
  );
};
SvgSiPinAlt1.displayName = "SvgSiPinAlt1";
const ForwardRef = forwardRef(SvgSiPinAlt1);
const Memo = memo(ForwardRef);
export default Memo;
