// packages/svelte/src/Fill/SiUser.svelte
<script>
  const inner = "<path fill=\"currentColor\" d=\"M6.25 7a5.75 5.75 0 1 1 11.5 0 5.75 5.75 0 0 1-11.5 0M11.798 14.261a1 1 0 0 1 .13-.011h.144q.066 0 .13.011l7.295 1.283.038.008c1.344.31 2.788 1.163 3.069 2.82l.004.029.114.877v.002c.264 2.009-1.329 3.47-3.21 3.47a1 1 0 0 1-.124-.01h-14.9c-1.881 0-3.475-1.462-3.21-3.472l.114-.869.005-.03c.28-1.627 1.736-2.528 3.077-2.819l.029-.006z\"/>";
  let { title, ...rest } = $props();
</script>

<svg
  xmlns="http://www.w3.org/2000/svg"
  width="1em"
  height="1em"
  fill="none"
  viewBox="0 0 24 24"
  aria-hidden={title ? undefined : 'true'}
  {...rest}
>
  {#if title}<title>{title}</title>{/if}
  {@html inner}
</svg>

// packages/react/src/Fill/SiUser.js
import * as React from "react";
import { forwardRef, memo } from "react";
import { useId } from "react";
const SvgSiUser = ({ title, titleId, ...props }, ref) => {
  const generatedId = useId();
  const validTitleId = titleId || generatedId;
  const isTitlePresent = !!title;
  return (
    <svg
      width="1em"
      height="1em"
      fill="none"
      viewBox="0 0 24 24"
      aria-hidden={!isTitlePresent}
      aria-labelledby={titleId}
      ref={ref}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fill="currentColor"
        d="M6.25 7a5.75 5.75 0 1 1 11.5 0 5.75 5.75 0 0 1-11.5 0m5.548 7.261a1 1 0 0 1 .13-.011h.144q.066 0 .13.011l7.295 1.283.038.008c1.344.31 2.788 1.163 3.069 2.82l.004.029.114.877v.002c.264 2.009-1.329 3.47-3.21 3.47a1 1 0 0 1-.124-.01h-14.9c-1.881 0-3.475-1.462-3.21-3.472l.114-.869.005-.03c.28-1.627 1.736-2.528 3.077-2.819l.029-.006z"
      />
    </svg>
  );
};
SvgSiUser.displayName = "SvgSiUser";
const ForwardRef = forwardRef(SvgSiUser);
const Memo = memo(ForwardRef);
export default Memo;
