// packages/svelte/src/Line/SiBriefcaseMedical.svelte
<script>
  const inner = "<path fill=\"currentColor\" d=\"M9 13.25a.75.75 0 0 0 0 1.5v-1.5m6 1.5a.75.75 0 0 0 0-1.5v1.5M11.25 17a.75.75 0 0 0 1.5 0h-1.5m1.5-6a.75.75 0 0 0-1.5 0h1.5M4.4 7v.75h15.2v-1.5H4.4zm15.2 0v.75c.911 0 1.65.739 1.65 1.65h1.5a3.15 3.15 0 0 0-3.15-3.15zM22 9.4h-.75v9.2h1.5V9.4zm0 9.2h-.75a1.65 1.65 0 0 1-1.65 1.65v1.5a3.15 3.15 0 0 0 3.15-3.15zM19.6 21v-.75H4.4v1.5h15.2zM4.4 21v-.75a1.65 1.65 0 0 1-1.65-1.65h-1.5a3.15 3.15 0 0 0 3.15 3.15zM2 18.6h.75V9.4h-1.5v9.2zm0-9.2h.75c0-.911.739-1.65 1.65-1.65v-1.5A3.15 3.15 0 0 0 1.25 9.4zM9 14v.75h6v-1.5H9zm3 3h.75v-6h-1.5v6zM9.8 4v.75h4.4v-1.5H9.8zm4.4 0v.75a.05.05 0 0 1 .05.05h1.5a1.55 1.55 0 0 0-1.55-1.55zm.8.8h-.75V7h1.5V4.8zM9 7h.75V4.8h-1.5V7zm0-2.2h.75a.05.05 0 0 1 .05-.05v-1.5A1.55 1.55 0 0 0 8.25 4.8z\"/>";
  let { title, ...rest } = $props();
</script>

<svg
  xmlns="http://www.w3.org/2000/svg"
  width="1em"
  height="1em"
  fill="none"
  viewBox="0 0 24 24"
  aria-hidden={title ? undefined : 'true'}
  {...rest}
>
  {#if title}<title>{title}</title>{/if}
  {@html inner}
</svg>

// packages/react/src/Line/SiBriefcaseMedical.js
import * as React from "react";
import { forwardRef, memo } from "react";
import { useId } from "react";
const SvgSiBriefcaseMedical = ({ title, titleId, ...props }, ref) => {
  const generatedId = useId();
  const validTitleId = titleId || generatedId;
  const isTitlePresent = !!title;
  return (
    <svg
      width="1em"
      height="1em"
      fill="none"
      viewBox="0 0 24 24"
      aria-hidden={!isTitlePresent}
      aria-labelledby={titleId}
      ref={ref}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fill="currentColor"
        d="M9 13.25a.75.75 0 0 0 0 1.5zm6 1.5a.75.75 0 0 0 0-1.5zM11.25 17a.75.75 0 0 0 1.5 0zm1.5-6a.75.75 0 0 0-1.5 0zM4.4 7v.75h15.2v-1.5H4.4zm15.2 0v.75c.911 0 1.65.739 1.65 1.65h1.5a3.15 3.15 0 0 0-3.15-3.15zM22 9.4h-.75v9.2h1.5V9.4zm0 9.2h-.75a1.65 1.65 0 0 1-1.65 1.65v1.5a3.15 3.15 0 0 0 3.15-3.15zM19.6 21v-.75H4.4v1.5h15.2zM4.4 21v-.75a1.65 1.65 0 0 1-1.65-1.65h-1.5a3.15 3.15 0 0 0 3.15 3.15zM2 18.6h.75V9.4h-1.5v9.2zm0-9.2h.75c0-.911.739-1.65 1.65-1.65v-1.5A3.15 3.15 0 0 0 1.25 9.4zM9 14v.75h6v-1.5H9zm3 3h.75v-6h-1.5v6zM9.8 4v.75h4.4v-1.5H9.8zm4.4 0v.75a.05.05 0 0 1 .05.05h1.5a1.55 1.55 0 0 0-1.55-1.55zm.8.8h-.75V7h1.5V4.8zM9 7h.75V4.8h-1.5V7zm0-2.2h.75a.05.05 0 0 1 .05-.05v-1.5A1.55 1.55 0 0 0 8.25 4.8z"
      />
    </svg>
  );
};
SvgSiBriefcaseMedical.displayName = "SvgSiBriefcaseMedical";
const ForwardRef = forwardRef(SvgSiBriefcaseMedical);
const Memo = memo(ForwardRef);
export default Memo;
