// packages/svelte/src/Duotone/SiDownTwoHeaded.svelte
<script>
  const inner = "<path stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"1.5\" d=\"M12 4v16m0 0-4-4m4 4 4-4m-8-5 4 4 4-4\"/>";
  let { title, ...rest } = $props();
</script>

<svg
  xmlns="http://www.w3.org/2000/svg"
  width="1em"
  height="1em"
  fill="none"
  viewBox="0 0 24 24"
  aria-hidden={title ? undefined : 'true'}
  {...rest}
>
  {#if title}<title>{title}</title>{/if}
  {@html inner}
</svg>

// packages/react/src/Line/SiDownTwoHeaded.js
import * as React from "react";
import { forwardRef, memo } from "react";
import { useId } from "react";
const SvgSiDownTwoHeaded = ({ title, titleId, ...props }, ref) => {
  const generatedId = useId();
  const validTitleId = titleId || generatedId;
  const isTitlePresent = !!title;
  return (
    <svg
      width="1em"
      height="1em"
      fill="none"
      viewBox="0 0 24 24"
      aria-hidden={!isTitlePresent}
      aria-labelledby={titleId}
      ref={ref}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={1.5}
        d="M12 4v16m0 0-4-4m4 4 4-4m-8-5 4 4 4-4"
      />
    </svg>
  );
};
SvgSiDownTwoHeaded.displayName = "SvgSiDownTwoHeaded";
const ForwardRef = forwardRef(SvgSiDownTwoHeaded);
const Memo = memo(ForwardRef);
export default Memo;
