// packages/svelte/src/Line/SiFlowCascade.svelte
<script>
  const inner = "<path stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-miterlimit=\"10\" stroke-width=\"1.5\" d=\"M7 6a2 2 0 1 0 0-4 2 2 0 0 0 0 4m0 0v10c0 2.2 1.694 4 3.765 4H15M7 6v3c0 2.2 1.694 4 3.765 4H15m0 7a2 2 0 1 0 4 0 2 2 0 0 0-4 0m0-7a2 2 0 1 0 4 0 2 2 0 0 0-4 0\"/>";
  let { title, ...rest } = $props();
</script>

<svg
  xmlns="http://www.w3.org/2000/svg"
  width="1em"
  height="1em"
  fill="none"
  viewBox="0 0 24 24"
  aria-hidden={title ? undefined : 'true'}
  {...rest}
>
  {#if title}<title>{title}</title>{/if}
  {@html inner}
</svg>

// packages/react/src/Line/SiFlowCascade.js
import * as React from "react";
import { forwardRef, memo } from "react";
import { useId } from "react";
const SvgSiFlowCascade = ({ title, titleId, ...props }, ref) => {
  const generatedId = useId();
  const validTitleId = titleId || generatedId;
  const isTitlePresent = !!title;
  return (
    <svg
      width="1em"
      height="1em"
      fill="none"
      viewBox="0 0 24 24"
      aria-hidden={!isTitlePresent}
      aria-labelledby={titleId}
      ref={ref}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeMiterlimit={10}
        strokeWidth={1.5}
        d="M7 6a2 2 0 1 0 0-4 2 2 0 0 0 0 4m0 0v10c0 2.2 1.694 4 3.765 4H15M7 6v3c0 2.2 1.694 4 3.765 4H15m0 7a2 2 0 1 0 4 0 2 2 0 0 0-4 0m0-7a2 2 0 1 0 4 0 2 2 0 0 0-4 0"
      />
    </svg>
  );
};
SvgSiFlowCascade.displayName = "SvgSiFlowCascade";
const ForwardRef = forwardRef(SvgSiFlowCascade);
const Memo = memo(ForwardRef);
export default Memo;
